name: seoul_pet_adoption
description: "서울동물복지지원센터에 입소해 있는 유기동물을 표시하는 앱입니다."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 상태 관리
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # 라우팅
  go_router: ^15.2.0
  # 네트워크
  dio: ^5.4.0
  # 유틸리티
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # UI
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0
  youtube_player_flutter: ^9.1.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_functions: ^5.5.2
  url_launcher: ^6.3.1
  swipeable_page_route: ^0.4.7
  shared_preferences: ^2.5.3
  flutter_linkify: ^6.0.0
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/fonts/
    - assets/images/
#    - shorebird.yaml
  fonts:
    - family: SeoulHangangB
      fonts:
        - asset: assets/fonts/SeoulHangangB.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#5F8F3C"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
